# Generated by Django 4.1.3 on 2022-12-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_post_caption_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isPublic',
        ),
    ]
