# Generated by Django 4.1.3 on 2023-01-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_post_ispublic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='no_of_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
    ]
