# Generated by Django 4.1.3 on 2022-12-06 22:30

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songfile', models.FileField(help_text='Upload your song', upload_to=audio.models.song_path, verbose_name='MP3 File')),
                ('album', models.CharField(help_text='Enter the name of the album', max_length=100, verbose_name='Name of the album')),
                ('title', models.CharField(help_text='Enter the name of the song', max_length=100, verbose_name='Name of the song')),
                ('artist', models.CharField(help_text='Enter the name of the artist', max_length=100, verbose_name='Name of the artist')),
                ('tracktotal', models.IntegerField(help_text='Enter the total number of tracks on the album', verbose_name='Total number of tracks on the album')),
                ('date', models.IntegerField(help_text='Enter the year of the albums release', verbose_name='Year of the albums release')),
                ('tracknumber', models.IntegerField(help_text='Enter the track number', verbose_name='Track number')),
                ('filetype', models.CharField(help_text='Enter the file type', max_length=20, verbose_name='File type')),
                ('runtime', models.IntegerField(help_text='Enter the full length of the song', verbose_name='Full length of the song')),
                ('genre', models.CharField(help_text='Enter the genre', max_length=100, verbose_name='Genre')),
                ('disc', models.IntegerField(help_text='Enter the total number of discs', verbose_name='Total number of discs')),
                ('lyrics', models.CharField(help_text='Enter the lyrics', max_length=500, verbose_name='Lyrics')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
