# Generated by Django 4.1.3 on 2022-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='date',
            field=models.CharField(help_text='Enter the year of the albums release', max_length=20, verbose_name='Year of the albums release'),
        ),
    ]
