# Generated by Django 4.1.3 on 2022-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_songs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='tracknumber',
            field=models.IntegerField(help_text='Enter the track number', null=True, verbose_name='Track number'),
        ),
    ]
