# Generated by Django 4.1.3 on 2022-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_songs_tracknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='runtime',
            field=models.IntegerField(default=1000, help_text='Enter the full length of the song', verbose_name='Full length of the song'),
        ),
    ]
