# Generated by Django 4.1.3 on 2022-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_alter_songs_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='disc',
            field=models.IntegerField(default=1, help_text='Enter the total number of discs', verbose_name='Total number of discs'),
        ),
    ]
