version: "3"
services:
  db:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'database-core'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    healthcheck:
      test: mysql database-core --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    expose:
      - 3306
      - 33060

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    container_name: database-core
    restart: always
    command:
      - /bin/bash
      - -c
      - |
       python manage.py migrate
       python manage.py runserver 0.0.0.0:8000